/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.5.1/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building a CLI application
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    mavenCentral()
    maven {
        //url = uri("http://maven.imagej.net/content/repositories/public/") // needed for rosuda
        url = uri("https://maven2.pavlab.msl.ubc.ca/") // needed for rosuda
    }
    flatDir{
        dirs("lib")
        dirs("lib/R")
    }
}

dependencies {
    // This dependency is used by the application.
    implementation("com.google.guava:guava:27.1-jre")
    implementation ("mysql:mysql-connector-java:5.1.48")
    implementation ("org.jdesktop:appframework:1.0.3")
    //compile("org.rosuda.REngine:REngine:2.1.0")
    // https://mvnrepository.com/artifact/RoSuDA/JRI
    //compile("RoSuDA:JRI:0.5-0")
    //compile("org.rosuda:jri:0.8-8")
    implementation ("javax.help:javahelp:2.0.05")
    implementation ("org.swinglabs:swing-layout:1.0.3")
    implementation ("org.swinglabs:swing-worker:1.1")
    implementation (group = "", name = "SevenZip")
    implementation (group = "", name = "jgraphx", version = "2.0.0.1")
    implementation (group = "", name = "javaGD")
    implementation (group = "", name = "REngine")
    implementation (group = "", name = "JRI")
    implementation (group = "", name = "JRIEngine")
    implementation (group = "org.jbundle.util.jcalendarbutton", name = "org.jbundle.util.jcalendarbutton", version = "1.6.4")
    // Use JUnit test framework
    testImplementation("junit:junit:4.12")
}

application {
    // Define the main class for the application
    mainClassName = "edacc.EDACCApp"
}
